#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev
mkdir -p /share
mount -t 9p -o trans=virtio,version=9p2000.L hostshare /share
echo "=== mymalloc VM is up ==="
exec /bin/sh
